# Generated by Django 4.2 on 2025-04-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='consulta',
            new_name='especialidade',
        ),
    ]
